# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ab382cb287cd9e04414b47350da013eccfef469971b9fae7dcc05967c7c2bdb383c208fd01374e5b20a2bb22f3f2a09d1a783f87647ce7891f87a0d66e3dbae
  publish_key: pub-c-9a6777d4-ac4d-4837-a668-b68db7892b18
  subscribe_key: sub-c-67b603d8-7c35-11e4-8ce0-02ee2ddab7fe
  secret_key: sec-c-MmIzMjlhNjktYTIxMy00ZDlhLWJmZTItNDkxODUwNzlmYTZm
  # client_id: 37d9c914-9ade-43ef-93a0-3ae66be6230b
  # client_secret: i9NEyE1paYxlhvD9gmU8GA57n3ZKiWn1KZyiNdjabZ8
  # client_id: 183cfc01-342c-4293-8536-a65ed433cde8
  # client_secret: ao3CvWFMCXRqwhuvQR3G1MGLsrTWm81doZkDEwjY2ps
  client_secret: 9o88I0wxCnQIuYmcJGTzmFSVMiT4R9m26kgXo3FFYHs
  client_id: 950c0a4f-6a09-4e71-93bc-63de197e7817

test:
  secret_key_base: 4c8855c7805917865222edc0b051eb140ddc68a1e675726eb0214644079eb533cbdcd37c74a37a0845248b9f80e0cfc9633eb80f2c02dc404bb809bb6ecadce8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  client_secret: 9o88I0wxCnQIuYmcJGTzmFSVMiT4R9m26kgXo3FFYHs
  client_id: 950c0a4f-6a09-4e71-93bc-63de197e7817
  # client_id: 183cfc01-342c-4293-8536-a65ed433cde8
  # client_secret: ao3CvWFMCXRqwhuvQR3G1MGLsrTWm81doZkDEwjY2ps
  # client_id: 37d9c914-9ade-43ef-93a0-3ae66be6230b
  # client_secret: i9NEyE1paYxlhvD9gmU8GA57n3ZKiWn1KZyiNdjabZ8
  secret_key_base: 31af52a55eaefa0cadab931e614e82322fcdc1edf538a39d94ff185851684215b489d4c1ee6da7694cad6ebf894c821fd9a6104d8419903eb1009967a7f9e6d6
  publish_key: pub-c-9a6777d4-ac4d-4837-a668-b68db7892b18
  subscribe_key: sub-c-67b603d8-7c35-11e4-8ce0-02ee2ddab7fe
  secret_key: sec-c-MmIzMjlhNjktYTIxMy00ZDlhLWJmZTItNDkxODUwNzlmYTZm